### PR TITLE
Feature/pk modifications

### PR DESCRIPTION
**Pull request by kaczor1984**
I know its not perfect... but I have work for now and I didn't have a lot  of time :)

To run the 'background jobs' you will need to start the sidekiq (and of course the redis-server).

I did not do the second part of task 5 (the tests).
I also did not test any part of my code.

I have also ignored the errors that could happen in case of adding/removing comments.
I didnt know what did you mean in the 'extending' of the movies API. You wanted it to contain movies and genres at the same time ?

edit:
I've checked the tests for the parenthesis but it doesn't look perfect.

### CODE REVIEW

**Comment by mpiask** [comment]
Hey @kaczor1984,
Please take one more look at the instructions:
* Do not fork the repository - clone it
* Put solutions for tasks in separate pull requests with descriptive commits, merge them to master branch after all
These two points are really important for your solutions to be readable. Could you take a minute to clean this commit history?

**Comment by kaczor1984** [comment]
Ok but how do i do a pull request to a clone of your code.
I get a message like that:
ERROR: Permission to netguru-training/pairguru.git denied to kaczor1984.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

regards,
Piotr Kaczorek

wt., 9 kwi 2019 o 11:32 Maciej Piaskowski <notifications@github.com>
napisał(a):

**Comment by kaczor1984** [comment]
Ok w takim wypadku przesyłam wam rozwiązania spakowane do ZIP-a.   pozdrawiam,  Piotr Kaczorek

**Comment by kaczor1984** [comment]
Hello,

Did you get my results from a different email address (in zip format)?
And are you checking it ?

regards,
Piotr

wt., 9 kwi 2019 o 13:31 Maciej Piaskowski <notifications@github.com>
napisał(a):

**Comment by mpiask** [comment]
No, I haven’t received them.

**Comment by kaczor1984** [comment]
So may I have your personal address ? I will send them to it (google blocks
sending any zip files).

regards,
Piotr

czw., 11 kwi 2019 o 14:23 Maciej Piaskowski <notifications@github.com>
napisał(a):

> No, I haven’t received them.
>

**Comment by mpiask** [comment]
Personally I use google too. You may create bundle file instead of zip. It should pass.
https://git-scm.com/docs/git-bundle <https://git-scm.com/docs/git-bundle>

**Comment by kaczor1984** [comment]
Hi,

I understand you did receive my solutions sent to you via my Dropbox
account ?
And about that bundle... If I was unable to push my clone to your github
then I guess I will also be unable to push the bundle to it.

regards,
Piotr

czw., 11 kwi 2019 o 14:35 Maciej Piaskowski <notifications@github.com>
napisał(a):

> Personally I use google too. You may create bundle file instead of zip. It
> should pass.
> https://git-scm.com/docs/git-bundle <https://git-scm.com/docs/git-bundle>
>

**Comment by mpiask** [comment]
Hey @kaczor1984,
We haven't received any attachments from you. Please notice that this conversation is hosted by Github, so it is possible that it does not support attaching files through email.
You won't be able to push solutions to our github from a cloned repo. You can do it either by hosting it on your account or by bundling it into a file, which you can then send by an email, so you don't have to have any specific push rights to deliver it.
While sending files please ensure that you use our recruitment email hosted at workable.com, not the one we use right now at github.com.
Fingers crossed,
MP

**Comment by kaczor1984** [comment]
Hej Maciek,

But I used your email from github = maciej.piaskowski@netguru.pl. I should
send it also to some other address ?

greetings,
Piotr

pt., 12 kwi 2019 o 12:36 Maciej Piaskowski <notifications@github.com>
napisał(a):

**Pull request closed without merging**
